### ISSUE TITLE
vim will freeze using v2.3.0

### ISSUE THREAD

**Issue by kepbod** [bradford-smith94/quick-scope#1]
Hi. Thanks so much for continuing to maintain this repo. I found my Vim will freeze after I update quick-scope to v2.3.0, and the v2.2.0 of quick-scope works well. So I suspect there are some problems in v2.3.0.

**Comment by bradford-smith94** [comment]
Thanks for bringing this to my attention. I set `g:qs_highlight_on_keys = [ f, F, t, T ]` and the issue doesn't occur so I had no idea this issue existed.

Removing the setting I am able to reproduce what I believe you are experiencing. 

For now you can either use that setting as a workaround (it's actually my preferred way of using the plugin) or you can use v2.2.0. I will try to get this sorted out as quick as I can.
