### ISSUE TITLE
Restore previous (not default) <c-c> functionality

### ISSUE THREAD

**Issue by brianbuccola** [bradford-smith94/quick-scope#2]
Hi, and let me echo thanks for taking over this plugin. Here's my issue: I use [vim-searchant](https://github.com/timakro/vim-searchant), which maps `<c-c>` to stop searching (technically, to `<Plug>SearchantStop`). However, quick-scope contains the following [lines](https://github.com/bradford-smith94/quick-scope/blob/master/plugin/quick_scope.vim#L401-L402):

```vim
" This line also causes getchar() to cleanly cancel on a <c-c>.
execute 'nnoremap <silent> <c-c> <c-c>'
```

So what happens is that after I press `f`, `t`, etc. to start a quick-scope find, my vim-searchant `<c-c>` mapping gets overridden.

For the moment, I've simply changed the relevant line to:

```vim
execute 'nmap <c-c> <Plug>SearchantStop'
```

and this works just fine. Ideally, though, the plugin would check if `<c-c>` is already mapped to something, save that mapping to a variable if so, and then map `<c-c>` back to what it previously was.

My vimscript isn't good enough to do this out on the fly, hence the issue report.

**Comment by bradford-smith94** [comment]
I completely agree, I should be able to handle this later today.

**Comment by brianbuccola** [comment]
Thanks! BTW, I just realized I didn't specify what "the relevant line" is. I meant to say that I changed [this line](https://github.com/bradford-smith94/quick-scope/blob/master/plugin/quick_scope.vim#L425)...

```vim
execute 'nunmap <c-c>'
```

...to...

```vim
execute 'nmap <c-c> <Plug>SearchantStop'
```
