### ISSUE TITLE
Bug when pressing r

### ISSUE THREAD

**Issue by rainerborene** [bradford-smith94/quick-scope#3]
Bug

Try to press `fr` on the following line (`^` is the cursor position):
```VimL
^"   au ColorScheme * hi! link Sneak Search
```
Then you'll see the following error message:
```
E11: Invalid in command-line window; <CR> executes, CTRL-C quits
E11: Invalid in command-line window; <CR> executes, CTRL-C quits
Error detected while processing function quick_scope#DoubleTap[7]..quick_scope#HighlightLine[9]..<SNR>103_get_highlight_patterns:
line   59:
E714: List required
Error detected while processing function quick_scope#DoubleTap[7]..quick_scope#HighlightLine:
line    9:
E714: List required
```

**Comment by bradford-smith94** [comment]
I was able to reproduce, except I don't get the `E11: ...` lines. I think they may not be related to quick-scope, the rest of the output definitely is and I am pushing a fix now.

Feel free to reopen this issue if you still get the `E11`s with the fix.

**Comment by rainerborene** [comment]
It works. 👍
